### ISSUE TITLE
Texture on Glass Doors & Trapdoors has small defects.

### ISSUE THREAD

**Issue by FrostWizard4** [FrostWizard4/Neutrino#1]
Texture on Glass Doors & Trapdoors on the top of the door and the side of the trapdoor has minor defects, have not taken the time to inspect rigorously, suspect it is in the `blockstates` JSON files

**Comment by srwxr-xr-x** [comment]
Fixed some of the defects, (specifically, the handle showing on the sides) but because the texture is clear in the middle, it will be clear on one edge of the side, labelling as `won't fix`, but solutions will be happily accepted.
