### ISSUE TITLE
Cannot be used on dedicated servers.

### ISSUE THREAD

**Issue by Giggitybyte** [FrostWizard4/Neutrino#12]
There are several usages of `MinecraftClient.getInstance()` [here](https://github.com/FrostWizard4/Neutrino/blob/4f0e85181322c6ac38829e339b3bcd35070904a6/src/main/java/com/frostwizard4/Neutrino/Artifacts/SoulHealerArtifact.java#L29), [here](https://github.com/FrostWizard4/Neutrino/blob/fa8af209e42961b034114bc2b42325fe4fe24a3d/src/main/java/com/frostwizard4/Neutrino/Artifacts/LightningRodArtifact.java#L30), and [here](https://github.com/FrostWizard4/Neutrino/blob/a78bc555f86376caded83975ab3c749500d74292/src/main/java/com/frostwizard4/Neutrino/mixin/PlayerEntityMixin.java#L30) which will cause a crash when this mod is loaded on a dedicated server.

![log screenshot](https://s.thegiggitybyte.me/BEPtK.png)

**Comment by srwxr-xr-x** [comment]
Yea, this was an issue because of the way minecraft handles servers and clients, fortunately the mod works on servers now as far as I can see!
Note that for some reason the Lightning rod doesn't work, investigating the issue now!
