### ISSUE TITLE
Please a config?

### ISSUE THREAD

**Issue by OtherMongrel** [FrostWizard4/Neutrino#21]
thank you very much for ur mod it's very good! some aspects of it don't fit my server so it would be great if every feature was togglable like actually additions

**Comment by K0-RR** [comment]
Sadly config screen got removed in the 0.5.0 release - https://github.com/FrostWizard4/Neutrino/releases/tag/v0.5.0
You can now only use a text editor to edit neutrino.conf

**Comment by srwxr-xr-x** [comment]
Yea @RDKRACZ is right, I got rid of it to limit dependencies, because I really dislike them :p. I could add them back as optional dependencies if others wanted it, but right now it's ```neutrino.conf``` & ```neutrino-dungeons.conf``` for disabling minecraft dungeons' items.
