### ISSUE TITLE
Place the config in config folder 

### ISSUE THREAD

**Issue by TheRanker** [FrostWizard4/Neutrino#23]
**Is your feature request related to a problem? Please describe.**
Took me many many days to find your config for this mod... It's in the root folder and will not be shipped with standard configs for modpacks.

**Describe the solution you'd like**
Put it where it belongs, in the config folders not root 

**Describe alternatives you've considered**
My alternative, remove it from modpack. 

**Additional context**
Move the conf files from root , to inside the config folder like they are suppose to be for easy modification and shipping with modpacks.

**Comment by K0-RR** [comment]
Can confirm configs are misplaced

**Comment by srwxr-xr-x** [comment]
Added in v0.6.4
