### ISSUE TITLE
[BUG] Bed not working properly

### ISSUE THREAD

**Issue by JonnZth** [FrostWizard4/Neutrino#27]
**Bug description**
When I sleep in a bad at night, it wakes me up as if normal, but it's still at night. 

**To Reproduce**
1. Open the game
2. Play or set until night
3. Click on a bed
4. Wait until you get ejected from the bed
5. See error

**Expected behavior**
The night passed and it would be then morning.

**Desktop (please complete the following information):**
 - Fabric Loader Version: fabric-loader-0.12.8-1.18

**Additional context**
This mod was used together with the following mods: `Light Overlay, The Wild Update Mod, Zombified, FromTheShadows, Blast, Castle Dungeons, NPC Variety, Dark Waters, Simple Backpack, Animal Feeding Trough, Not Enough Crashes, Repurpuosed Structures, Presence Footsteps, Mouse Wheelie, Mod Menu, Wraith's Waystones, AdventureZ, Adorn, Blockus, Better Nether, REI, Hookshot, farsight, Sodium, Iris(Sildur's Vibrant Shaders), and the respective dependencies.`

**Comment by srwxr-xr-x** [comment]
This had to do with the alarm clock being coded improperly, this has been resolved and will be released soon.
