### ISSUE TITLE
[BUG]clock and compass tick crash again

### ISSUE THREAD

**Issue by TheRanker** [FrostWizard4/Neutrino#31]
**Describe the bug**
you know this bug well..... its back. if it was ever removed .
at net.minecraft.entity.player.PlayerEntity.handler$ggl000$neutrino$tickClockandCompass(PlayerEntity:32027)

**To Reproduce**
1. use Neutrino-0.6.9.jar, on fabric 1.18.2 with 0.13.3 and fabric-api-0.48.0+1.18.2
2. put a compass in your inventory
3. play the game

**Expected behavior**
no crash.

**Screenshots**

[crash-2022-03-29_21.46.34-server.txt](https://github.com/FrostWizard4/Neutrino/files/8375757/crash-2022-03-29_21.46.34-server.txt)

**Comment by TheButterbrotMan** [comment]
Oh no!

**Comment by srwxr-xr-x** [comment]
What in gods name
how is that even possible

**Comment by srwxr-xr-x** [comment]
Permanently fixed it, wasn't removed in the last update because of an error on my part from GitHub Desktop.
[https://github.com/FrostWizard4/Neutrino/releases/tag/v0.7.0](https://github.com/FrostWizard4/Neutrino/releases/tag/v0.7.0)
