### ISSUE TITLE
Add Dust Caves, Opposite of Lush Caves.

### ISSUE THREAD

**Issue by srwxr-xr-x** [FrostWizard4/Neutrino#7]
Discovered the idea for `Dust Caves` the Opposite of Lush Caves, Has been troubling to implement however.

**Comment by Expora8** [comment]
What's the issue?

**Comment by srwxr-xr-x** [comment]
I added a label called "Addition Needed", just a way to share Ideas and request help for Ideas

**Comment by srwxr-xr-x** [comment]
Closing to wait for 1.18 because it seems the Fabric Biome API changed a lot in 1.18 snapshots!
